CREATE TABLE IF NOT EXISTS EMPLOYEE(EMPLOYEE_ID INT(6), NAME VARCHAR(20), SALARY INT);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(100,'Jennifer',4400);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(100,'Jennifer',4400);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'Pat',6000);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'Pat',6000);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(103,'Den',11000);
SELECT * FROM EMPLOYEE;

# Using GROUP BY function
SELECT EMPLOYEE_ID, NAME, SALARY FROM EMPLOYEE GROUP BY EMPLOYEE_ID ORDER BY EMPLOYEE_ID;
SELECT DISTINCT(EMPLOYEE_ID), NAME, SALARY FROM EMPLOYEE;

# Using ROW_NUMBER Analytics Function
SELECT EMPLOYEE_ID, NAME, SALARY, ROW_NUMBER() OVER(PARTITION BY EMPLOYEE_ID, NAME, SALARY) AS ROW_NUMBERS FROM EMPLOYEE;

SELECT 
	EMPLOYEE_ID, 
    NAME, 
    SALARY 
FROM (SELECT 
		EMPLOYEE_ID, 
        NAME, 
        SALARY, 
        ROW_NUMBER() 
        OVER(PARTITION BY EMPLOYEE_ID, NAME, SALARY ORDER BY EMPLOYEE_ID) AS ROW_NUMBERS FROM EMPLOYEE) sub
        WHERE ROW_NUMBERS = 1;
